name: MelvuzeCustomItems
version: '${version}'
main: me.leopold95.melvuzecustomitems.CustomItems
api-version: '1.17'
depend:
  - MelvuzeItemsLib
  - CombatLogX
softdepend:
  - ChangeSkinX
  - SkinsRestorer

